#ifndef FW_CONFIG_H
#define FW_CONFIG_H

#define FW_IS_FULLSCREEN_ENABLED TRUE
#define FW_IS_FULLSCREEN_CHANGE_RESOLUTION TRUE
#define FW_IS_FULLSCREEN_BORDERLESS_ENABLED FALSE

#define FW_IS_MUSIC_ENABLED TRUE
#define FW_SOUND_READ_FILE_ENABLED FALSE
#define FW_SOUND_FILE_PATH "C:/projects/music.mod"

#define FW_WINDOW_NAME  "OFFSET OVERDRIVE - SPECTROX"

#define FW_FULLSCREEN_WIDTH  1920
#define FW_FULLSCREEN_HEIGHT 1080

#define FW_WINDOW_WIDTH  692
#define FW_WINDOW_HEIGHT 540

#define FW_RENDER_WIDTH  346
#define FW_RENDER_HEIGHT 270

#define FW_STARTUP_DELAY_MILLIS 0

#define FW_SCANLINES_ENABLED FALSE
#define FW_SCANLINES_ALPHA .3f


#endif
